// <auto-generated />
namespace Movies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMin18YearsOldClassValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMin18YearsOldClassValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251943002_AddMin18YearsOldClassValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
